### ISSUE TITLE
[feat] 레이아웃 구현

### ISSUE THREAD

**Issue by jsh1147** [jsh1147/codeit-FE10-WINE#1]
## 📝 Description

- 레이아웃 구현

## ✅ To-Do List

- [x] 레이아웃 컴포넌트
- [x] 메뉴 드롭다운 컴포넌트
- [x] 유저 상태 기능
- [x] 헤더 컴포넌트
- [x] 유저 상태에 따라 헤더 변화
