### ISSUE TITLE
[feat] 와인 목록 페이지 - 반응형 UI 구현

### ISSUE THREAD

**Issue by mulddang2** [jsh1147/codeit-FE10-WINE#10]
## 📝 Description

- 태블릿, 모바일에서 달라지는 UI  적용, 반응형 적용하기

## ✅ To-Do List

- [x] 이번달 추천 와인에서 **디스플레이 크기별 슬라이더 갯수** 달라진다.
- [x] **태블릿 크기 기기 이하**에서는 **좌측 필터링 기능 부분이 검색결과 상단으로 이동**된다.
- [x] **모바일 크기**에서는 **와인 등록하기 버튼이 최하단에 고정**되어 있다.
