### ISSUE TITLE
[style] 별점 컴포넌트 UI 수정

### ISSUE THREAD

**Issue by SHAKALOHANA** [jsh1147/codeit-FE10-WINE#27]
## 📝 Description

- 별점 컴포넌트 UI 수정

## ✅ To-Do List

- []  평균 점수 표시   
- []  평균 점수 별점으로 표시 (내림)
- []  각 점수별 득점수를 그래프로 표현
- [] 리뷰 남기기 버튼 구현 (모달 ->)
