### ISSUE TITLE
[feat] 등록한 와인 수정하기 모달 + 내프로필 페이지 보완

### ISSUE THREAD

**Issue by swim-kim** [jsh1147/codeit-FE10-WINE#29]
## 📝 Description
- 내가 등록한 와인 수정하기 모달입니다
- 내프로필 페이지 보완 사항 (이메일, 이미지, 인풋 placeholder)

## ✅ To-Do List

와인 수정하기 모달
- [x] 수정하기 클릭시 수정하기 모달이 나타납니다
- [x] 모달 ui 작업
- [x] 와인 이름, 가격, 원산지, 타입, 이미지를 수정할 수 있습니다

내 프로필 컴포넌트 보완
- [x] 로컬스토리지에 저장된 이메일을 가져오도록 한다
- [x] 닉네임 수정 placeholder에 기존 닉네임이 뜨도록한다
