### ISSUE TITLE
[refactor] 레이아웃 & 랜딩 페이지 개선

### ISSUE THREAD

**Issue by jsh1147** [jsh1147/codeit-FE10-WINE#30]
## 📝 Description

- 레이아웃 & 랜딩 페이지 개선

## ✅ To-Do List

- [ ] 헤더 z-index 수정
- [ ] 랜딩 페이지 버튼 추가 및 페이지 전환 로직 변경
- [ ] svg 이미지 컴포넌트화
