### ISSUE TITLE
[chore] 와인 상세 페이지 - 컴포넌트 파일 위치 변경

### ISSUE THREAD

**Issue by SHAKALOHANA** [jsh1147/codeit-FE10-WINE#34]
## 📝 Description

-  와인 상세 페이지 - 컴포넌트 파일들의 위치 변경 (새로운 폴더로 이동)
- 기존 wines / wine
- 변경 후 wineDetail

## ✅ To-Do List

- [ ] wines/WineDetail.css.ts -> styles
- [ ] wines/ReviewList.tsx -> wineDetail
- [ ] wines/WineInfoSection.css.ts -> wineDetail
- [ ] wines/WineInfoSection.tsx -> wineDetail
- [ ] wine/WineRating.tsx -> wineDetail
- [ ] wine/WineRating.css.ts -> wineDetail
