### ISSUE TITLE
[feat] 내프로필 페이지 보완

### ISSUE THREAD

**Issue by swim-kim** [jsh1147/codeit-FE10-WINE#35]
## 📝 Description
내프로필 페이지 보완 사항 (이메일, 이미지, 인풋 placeholder)

## ✅ To-Do List

- [ ] 로컬스토리지에 저장된 이메일을 가져오도록 한다
- [ ] 이미지 호버시 이미지 수정 버튼이 뜬다
- [ ] 닉네임 수정 placeholder에 기존 닉네임이 뜨도록한다
