### ISSUE TITLE
[style] 와인 상세페이지, 리뷰리스트 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by SHAKALOHANA** [jsh1147/codeit-FE10-WINE#37]
## 📝 Description

- 와인 상세 페이지 - 리뷰 리스트 컴포넌트의 UI 구현

## ✅ To-Do List

- [ ] 유저 아이콘
- [ ] 유저 이름
- [ ] 리뷰 업데이트 시간 표시
- [ ] 좋아요 아이콘
- [ ] 설정 버튼 (수정하기 / 삭제하기)
- [ ] Aroma 5가지 
- [ ] 리뷰 내용
- [ ] 바디감 / 타닌 / 당도 / 산미 - 슬라이더 표현
