### ISSUE TITLE
[feat] 와인 상세 페이지 - "리뷰 남기기" 모달 구현

### ISSUE THREAD

**Issue by SHAKALOHANA** [jsh1147/codeit-FE10-WINE#45]
## 📝 Description

- [feat] 와인 상세 페이지 - "리뷰 남기기" 모달 구현

## ✅ To-Do List

- [ ] 모달 구현 - 우측 상단 x 닫기 버튼, 모달 외부 클릭 시 모달 창 닫기
- [ ] 와인 이름 표시
- [ ] 별점 아이콘 - 드래그 or 마우스 클릭을 통한 별점 기능 구현
- [ ] 후기 작성을 위한 텍스트 인풋
- [ ] 와인 맛 설정 - 슬라이드 구현
- [ ] 향(aroma) - 박스? 버튼? 클릭을 통해 설정 가능하도록 구현
- [ ] 리뷰 남기기 버튼 - API Post
