### ISSUE TITLE
[feat] 와인 목록 페이지 - 와인 등록 버튼 및 모달 기능 구현

### ISSUE THREAD

**Issue by mulddang2** [jsh1147/codeit-FE10-WINE#9]
## 📝 Description

- 와인 등록 모달 관련 기능 구현

## ✅ To-Do List

- [x] 등록 모달 퍼블리싱
- [x] 이름, 가격, 원산지, 사진, 타입 정보 입력 후, '와인 등록하기' 버튼 누르면 와인 등록한다.
- [x] 등록이 되면, 해당 와인 상세페이지로 이동한다.
- [x] 취소 버튼 클릭 시, 모달창 꺼지도록 한다.
- [x] 와인 사진을 png 등으로 확장자 한정하도록 한다.
